In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

In [ ]:
training_data = pd.read_csv("/content/drive/MyDrive/trainGOOG.csv")
testing_data = pd.read_csv("/content/drive/MyDrive/test_GOOG.csv")

In [ ]:
training_data.shape

(2517, 7)

In [ ]:
testing_data.shape

(252, 7)

In [ ]:
testing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       252 non-null    object 
 1   Open       252 non-null    float64
 2   High       252 non-null    float64
 3   Low        252 non-null    float64
 4   Close      252 non-null    float64
 5   Adj Close  252 non-null    float64
 6   Volume     252 non-null    int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 13.9+ KB


In [ ]:
testing_data.head()

Date        Open        High         Low       Close   Adj Close  \
0  2023-04-10  107.389999  107.970001  105.599998  106.949997  106.949997   
1  2023-04-11  106.919998  107.220001  105.279999  106.120003  106.120003   
2  2023-04-12  107.389999  107.586998  104.970001  105.220001  105.220001   
3  2023-04-13  106.470001  108.264999  106.440002  108.190002  108.190002   
4  2023-04-14  107.690002  109.580002  107.589996  109.459999  109.459999   

     Volume  
0  19741500  
1  18721300  
2  22761600  
3  21650700  
4  20758700

In [ ]:
training_data.head()

Date       Open       High        Low      Close  Adj Close  \
0  03-01-2011  14.856315  15.083214  14.856315  15.052330  15.052330   
1  04-01-2011  15.083962  15.097909  14.946975  14.996788  14.996788   
2  05-01-2011  14.945730  15.201272  14.945232  15.169890  15.169890   
3  06-01-2011  15.209989  15.403016  15.194298  15.280226  15.280226   
4  07-01-2011  15.340251  15.398533  15.196291  15.353451  15.353451   

      Volume  
0   94962614  
1   73253547  
2  101671667  
3   82620526  
4   84363033

In [ ]:
train_data = training_data.iloc[:,1:2].values
test_data = testing_data.iloc[:,1:2].values

In [ ]:
train_data.shape, training_data.shape,test_data.shape, testing_data.shape

((2517, 1), (2517, 7), (252, 1), (252, 7))

In [ ]:
train_data

array([[14.856315],
       [15.083962],
       [14.94573 ],
       ...,
       [89.389503],
       [88.100502],
       [86.771004]])

In [ ]:
scaler = MinMaxScaler()

In [ ]:
train_data = scaler.fit_transform(train_data)
test_data = scaler.fit_transform(test_data)

In [ ]:
train_data

array([[0.03841043],
       [0.04127679],
       [0.03953628],
       ...,
       [0.97687624],
       [0.96064611],
       [0.94390607]])

In [ ]:
X_train = []
y_train = []
X_test = []
y_test = []

In [ ]:
for i in range(50,2517):
  X_train.append(train_data[i-50:i,0])
  y_train.append(train_data[i,0])

X_train = np.array(X_train)
y_train = np.array(y_train)



In [ ]:
for i in range(50,252):
  X_test.append(test_data[i-50:i,0])
  y_test.append(test_data[i,0])

X_test = np.array(X_test)
y_test = np.array(y_test)

In [ ]:
X_test.shape,y_test.shape

((202, 50), (202,))

In [ ]:
X_train.shape, y_train.shape

((2467, 50), (2467,))

In [ ]:
X_train = X_train.reshape(2467,50,1)

In [ ]:
y_train.shape,X_train.shape

((2467,), (2467, 50, 1))

In [ ]:
model = keras.Sequential([
    keras.layers.SimpleRNN(100, input_shape = (50,1), activation = "relu", return_sequences = False),
    keras.layers.Dense(1, activation = "linear")
])

In [ ]:
model.compile(optimizer = "adam", loss = "mse", metrics = "accuracy")

In [ ]:
model.fit(X_train, y_train, epochs = 100, batch_size = 32)

Epoch 1/100
78/78 [==============================] - 2s 12ms/step - loss: 0.0153 - accuracy: 8.1070e-04
Epoch 2/100
78/78 [==============================] - 1s 11ms/step - loss: 1.5861e-04 - accuracy: 8.1070e-04
Epoch 3/100
78/78 [==============================] - 1s 11ms/step - loss: 1.2727e-04 - accuracy: 8.1070e-04
Epoch 4/100
78/78 [==============================] - 2s 24ms/step - loss: 1.3648e-04 - accuracy: 8.1070e-04
Epoch 5/100
78/78 [==============================] - 3s 36ms/step - loss: 1.2405e-04 - accuracy: 8.1070e-04
Epoch 6/100
78/78 [==============================] - 1s 15ms/step - loss: 1.2244e-04 - accuracy: 8.1070e-04
Epoch 7/100
78/78 [==============================] - 1s 12ms/step - loss: 1.3291e-04 - accuracy: 8.1070e-04
Epoch 8/100
78/78 [==============================] - 1s 12ms/step - loss: 1.1750e-04 - accuracy: 8.1070e-04
Epoch 9/100
78/78 [==============================] - 1s 12ms/step - loss: 1.3734e-04 - accuracy: 8.1070e-04
Epoch 10/100
78/78 [============

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 100)               10200     
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 10301 (40.24 KB)
Trainable params: 10301 (40.24 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
X_test.shape

(202, 50)

In [ ]:
model.evaluate(X_test, y_test)

7/7 [==============================] - 0s 7ms/step - loss: 0.0019 - accuracy: 0.0050


[0.0018769699381664395, 0.004950494971126318]

In [ ]:
model2 = keras.Sequential([
    keras.layers.LSTM(100, input_shape = (50,1), activation = "relu", return_sequences = False),
    keras.layers.Dense(1, activation = "linear")
])

In [ ]:
model2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 100)               40800     
                                                                 
 dense_2 (Dense)             (None, 1)                 101       
                                                                 
Total params: 40901 (159.77 KB)
Trainable params: 40901 (159.77 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model2.compile(optimizer = "adam", loss = "mse", metrics = "accuracy")

In [ ]:
model2.fit(X_train, y_train, epochs = 50, batch_size = 32)

Epoch 1/50
78/78 [==============================] - 4s 30ms/step - loss: 0.0291 - accuracy: 8.1070e-04
Epoch 2/50
78/78 [==============================] - 2s 30ms/step - loss: 4.2437e-04 - accuracy: 8.1070e-04
Epoch 3/50
78/78 [==============================] - 2s 30ms/step - loss: 3.4404e-04 - accuracy: 8.1070e-04
Epoch 4/50
78/78 [==============================] - 2s 30ms/step - loss: 2.9929e-04 - accuracy: 8.1070e-04
Epoch 5/50
78/78 [==============================] - 3s 43ms/step - loss: 2.9089e-04 - accuracy: 8.1070e-04
Epoch 6/50
78/78 [==============================] - 3s 32ms/step - loss: 2.9676e-04 - accuracy: 8.1070e-04
Epoch 7/50
78/78 [==============================] - 3s 35ms/step - loss: 2.3183e-04 - accuracy: 8.1070e-04
Epoch 8/50
78/78 [==============================] - 2s 30ms/step - loss: 2.5296e-04 - accuracy: 8.1070e-04
Epoch 9/50
78/78 [==============================] - 2s 30ms/step - loss: 2.3029e-04 - accuracy: 8.1070e-04
Epoch 10/50
78/78 [======================

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/HistoricalData_1713510106646.csv")

In [ ]:
df.head()

Date  Close/Last    Volume    Open    High     Low
0  04/18/2024      2398.0  195493.0  2377.9  2408.0  2377.2
1  04/17/2024      2388.4  279551.0  2398.0  2412.0  2370.7
2  04/16/2024      2407.8  290700.0  2399.1  2414.8  2379.2
3  04/15/2024      2383.0  336608.0  2369.4  2404.3  2340.2
4  04/12/2024      2374.1  463075.0  2389.4  2448.8  2350.6

In [ ]:
df_close = df.iloc[:,1:2].values

In [ ]:
df_close.shape

(1258, 1)

In [ ]:
df_test = df_close[:258,:]
df_train = df_close[258:,:]

In [ ]:
df_test.shape, df_train.shape

((258, 1), (1000, 1))

In [ ]:
df_train

In [ ]:
df_train = scaler.fit_transform(df_train)
df_test = scaler.fit_transform(df_test)

In [ ]:
df_train[:5,:]

array([[0.91773263],
       [0.94607474],
       [0.93917733],
       [0.94080762],
       [0.89277652]])

In [ ]:
X_train = []
y_train = []
X_test = []
y_test = []

In [ ]:
for i in range(25,1000):
  X_train.append(df_train[i-25:i,0])
  y_train.append(df_train[i,0])

X_train = np.array(X_train)
y_train = np.array(y_train)


In [ ]:
for i in range(25,258):
  X_test.append(df_test[i-25:i,0])
  y_test.append(df_test[i,0])

X_test = np.array(X_test)
y_test = np.array(y_test)

In [ ]:
X_train.shape, y_train.shape

((975, 25), (975,))

In [ ]:
X_test.shape, y_test.shape

((233, 25), (233,))

In [ ]:
X_train = X_train.reshape(975,25,1)
X_test = X_test.reshape(233,25,1)

In [ ]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((975, 25, 1), (975,), (233, 25, 1), (233,))

In [ ]:
model = keras.Sequential([
    keras.layers.SimpleRNN(100, input_shape = (25,1), activation = "relu", return_sequences = False),
    keras.layers.Dense(1, activation = "linear")
])

model.compile(optimizer = "adam", loss = "mse")


In [ ]:
model.fit(X_train, y_train, epochs = 100, batch_size = 10)

Epoch 1/100
98/98 [==============================] - 2s 6ms/step - loss: 0.0286
Epoch 2/100
98/98 [==============================] - 1s 5ms/step - loss: 9.3691e-04
Epoch 3/100
98/98 [==============================] - 1s 6ms/step - loss: 8.7550e-04
Epoch 4/100
98/98 [==============================] - 1s 6ms/step - loss: 8.2392e-04
Epoch 5/100
98/98 [==============================] - 1s 6ms/step - loss: 8.8761e-04
Epoch 6/100
98/98 [==============================] - 1s 6ms/step - loss: 7.7073e-04
Epoch 7/100
98/98 [==============================] - 1s 9ms/step - loss: 8.1021e-04
Epoch 8/100
98/98 [==============================] - 1s 10ms/step - loss: 7.2517e-04
Epoch 9/100
98/98 [==============================] - 1s 10ms/step - loss: 7.6556e-04
Epoch 10/100
98/98 [==============================] - 1s 10ms/step - loss: 7.3315e-04
Epoch 11/100
98/98 [==============================] - 1s 10ms/step - loss: 7.1535e-04
Epoch 12/100
98/98 [==============================] - 1s 10ms/step - loss:

In [ ]:
model.evaluate(X_test,y_test)

8/8 [==============================] - 0s 4ms/step - loss: 7.5602e-04


0.0007560232770629227

In [ ]:
model.predict(X_test)[:5,:]

8/8 [==============================] - 0s 3ms/step


array([[0.5891106 ],
       [0.6136205 ],
       [0.58936465],
       [0.62623805],
       [0.6209462 ]], dtype=float32)

In [ ]:
y_test[:5]

array([0.60590278, 0.58038194, 0.61944444, 0.6140625 , 0.57881944])